version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rerate_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    ports:
      - "13306:3306"
  backend:
    build: ./backend
    image: rerate_backend:1.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app:cached
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - packs:/app/public/packs
      - packs_test:/app/public/packs-test
    tmpfs:
      - /tmp
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: development
      DATABASE_URL: "mysql2://root:root@db"
      EDITOR: "vim"
      BUNDLE_PATH: "/app/vendor/bundle"
      BOOTSNAP_CACHE_DIR: "/app/vendor/bundle"
      WD_INSTALL_DIR: "/usr/local/bin"
      HISTFILE: "/app/log/.bash_history"
    depends_on:
      - db
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports: ["3001:3000"]
    user: root
    working_dir: /app
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/src
    command: "npm start"
    depends_on:
      - backend

volumes:
  mysql-data:
  bundle:
  node_modules:
  rails_cache:
  packs:
  packs_test:
